### ISSUE TITLE
webfront #1 :: Intro page image inserting problem

### ISSUE THREAD

**Issue by Goinging98** [laykis/OwnHub#1]
첫 메인 페이지에서 상대경로, 절대경로 모두 다 넣어봤는데 사진처럼 crack인 상태로 업로드가 됩니다..
추후 나중에 아코디언으로 업로드한 뒤, 그 경로를 불러오기를 하면 되려나요..?
![image](https://user-images.githubusercontent.com/38778937/179746052-2a0839bd-1b4b-4714-92cf-75dcc80428e3.png)

At the first intro page, I uploaded with path but it didn't work. 
After using Acordian, will this problem be solved..?

**Comment by garam0410** [comment]
```
<img src = {require('경로')} />
```

**Comment by laykis** [comment]
> ```
> <img src = {require('경로')} />
> ```

Thank you for your advice^^^^

**Comment by Goinging98** [comment]
Based on your advice @garam0410 , I can solve the problem!
Thank you! 
![image](https://user-images.githubusercontent.com/38778937/180362400-4ad934af-29e7-483d-a367-c152efba8f38.png)
